const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Plugins.Mouse,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.MoveTo.Acts.SetSpeed,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Keyboard.Cnds.OnKey
	];
};
self.C3_JsPropNameTable = [
	{"8Direções": 0},
	{RestritoAoLayout: 0},
	{spr_player: 0},
	{Mouse: 0},
	{MoverPara: 0},
	{spr_inimigo: 0},
	{ID: 0},
	{spr_spawner: 0},
	{Projétil: 0},
	{DestruirExternamente: 0},
	{spr_bala: 0},
	{HudBG: 0},
	{txt_score: 0},
	{txt_life: 0},
	{txt_clock: 0},
	{BG_Stars: 0},
	{txt_titulo: 0},
	{txt_Pressionar: 0},
	{Teclado: 0},
	{coracao: 0},
	{Caveira: 0},
	{Sprite: 0},
	{Áudio: 0},
	{Partículas: 0},
	{VelocidadeSpawn: 0},
	{enemyVelocidade: 0},
	{SpawnerRNG: 0},
	{score: 0},
	{Level: 0},
	{clock: 0},
	{Vida: 0}
];

self.InstanceType = {
	spr_player: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	spr_inimigo: class extends self.ISpriteInstance {},
	spr_spawner: class extends self.ISpriteInstance {},
	spr_bala: class extends self.ISpriteInstance {},
	HudBG: class extends self.ITiledBackgroundInstance {},
	txt_score: class extends self.ITextInstance {},
	txt_life: class extends self.ITextInstance {},
	txt_clock: class extends self.ITextInstance {},
	BG_Stars: class extends self.ISpriteInstance {},
	txt_titulo: class extends self.ITextInstance {},
	txt_Pressionar: class extends self.ITextInstance {},
	Teclado: class extends self.IInstance {},
	coracao: class extends self.ISpriteInstance {},
	Caveira: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Partículas: class extends self.IParticlesInstance {}
}